API/urls.py
from django.conf.urls import url
from . import views as api_views
urlpatterns = [
    url(r'^Location', api_views.LocationTable.as_view(), name='LocationTableAPI'),
    url(r'^Questionnaire', api_views.QuestionnaireTable.as_view(), name='QuestionnaireTableAPI'),
    url(r'^Question', api_views.QuestionTable.as_view(), name='QuestionTableAPI'),
    url(r'^Answer', api_views.AnswerTable.as_view(), name='AnswerTableAPI'),
    url(r'^QA', api_views.QuestionAnswerTable.as_view(), name='QATableAPI'),
    url(r'^Logic', api_views.LogicTable.as_view(), name='LogicTableAPI'),
    url(r'^QRel', api_views.QRelTable.as_view(), name='QRelTableAPI'),
    url(r'^login', api_views.LoginView.as_view(), name='LoginAPI'),
    url(r'^Patients', api_views.PatientTable.as_view(), name='PatientAPI'),
    url(r'^PatientAssessment', api_views.PatientAssessmentTable.as_view(), name='PatientAPI'),
    url(r'^Response', api_views.QuestionResponseTable.as_view(), name='QuestionResponseAPI'),
    url(r'^Household', api_views.HouseholeTable.as_view(), name='HouseholdAPI'),
]

Builder/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.questionnaires, name='questionnaires'),
    path('create/', views.newQuestionnaire, name='newQuestionnaire'),
    path('create/question/<int:questionnaire_id>/', views.addQuestions, name='addQuestions'),
    path('create/question/<int:questionnaire_id>/answers/<int:question_id>/', views.addAnswers, name='addAnswers'),
    path('create/question/<int:questionnaire_id>/logic', views.addLogic, name='addLogic'),
    path('ajax/', views.ajaxAnswer, name='ajax_answer'),
    path('setactive/', views.setActiveQnn, name='setActiveQnn'),
]

Dashboard/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView, name='dashboard'),
    path('ajax/', views.ajaxLocation, name='ajaxLocation'),
    path('ajax/patient', views.ajaxIncompletePatients, name='ajaxPatient'),
    path('data/', views.ajaxData, name='ajaxData'),
]

Locations/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.createLocation, name='createLocation'),
]

Reports/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chooseLocation, name='report_location'),
    path('qnn/<str:clusterID>/', views.chooseQuestionnaire, name='report_qnn'),
    path('qnn/<str:clusterID>/<str:questionnaireID>/', views.reportQnn, name='report')
]

Users/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getToken, name='getToken'),
    path('add/<str:token>/<str:username>/<str:email>/', views.addEnumerator, name='addEnum'),
    path('status/<int:status>', views.response_message, name='responseMessage'),
]

Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views

from API import views as api_views
from Website.Auth import views as website_auth_views
from Dashboard import views as dash_view
from Users import views as enum_view
from Locations import views as loc_view
from Home import views as test_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path("", website_auth_views.home_view, name="home"),
    url('tables/', include(("API.urls", "API"), namespace="API")),
    url(r'^API-token-auth/', obtain_auth_token, name='api_token_auth'),
    path("users/", api_views.UserCreate.as_view(), name="user_create"),
    path("login/api", api_views.LoginView.as_view(), name="login_api"),
    url(r'^api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path("login/", csrf_exempt(website_auth_views.login_view), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    url('questionnaires/', include(("Builder.urls", "Builder"), namespace="Builder")),
    url('dashboard/', include(("Dashboard.urls", "Dashboard"), namespace="Dashboard")),
    url('enumerators/', include(("Users.urls", "Enumerator"), namespace="Enumerator")), 
    url('reports/', include(("Reports.urls", "Reports"), namespace="Reports")),
    url('locations/', include(("Locations.urls", "Locations"), namespace="Locations")),

    # For Loader.io Testing purposes
    # url('loaderio-5394cb69fc9debd1de2f68952e5fcea0', test_view.home, name="loaderIO")
    ]

Dashboard/models.py
from django.db import models

# Create your models here.

Dashboard/forms.py
from django import forms
from Questions.models import PatientAssessment
from Locations.models import *

class dashboardForm(forms.Form):
    country = forms.ChoiceField(label='Country', widget=forms.Select)
    region = forms.ChoiceField(label='Region', widget=forms.Select)
    cluster = forms.ChoiceField(label='Cluster', widget=forms.Select)

    def __init__(self, *args, **kwargs):
        super(dashboardForm, self).__init__(*args, **kwargs)
        emptyChoiceList = [('0', '----------')]
        countryList = [(country.locationID, country.locationName) for country in Location.objects.filter(parentLocID = -1)]
        allLocations = [(location.locationID, location.locationName) for location in Location.objects.all().exclude(pk = -1)]
        countryChoices = emptyChoiceList + countryList
        otherChoices = emptyChoiceList + allLocations
        self.fields['country'].choices = countryChoices
        self.fields['region'].choices = otherChoices
        self.fields['cluster'].choices = otherChoices

Dashboard/views.py
from django.shortcuts import render
from django.template import loader
from django.http import JsonResponse
from .forms import *
from Questions import models
from Locations import models
from API import serializers
from django.forms.models import model_to_dict

def DashboardView(request):
    form = dashboardForm()
    incomplete = PatientAssessment.objects.filter(questionnaireStatus = "INCOMPLETE").count()
    incomplete_patients = PatientAssessment.objects.filter(questionnaireStatus = "INCOMPLETE").values()
    complete = PatientAssessment.objects.filter(questionnaireStatus = "COMPLETE").count()
    sizes = [complete, incomplete]
    labels = ['Completed Assessment', 'Unfinished Assessment']
    context = {
        'form': form,
        'sizes': sizes,
        'labels': labels,
        'incomplete_patients': incomplete_patients,
    }
    return render(request, 'dashboard.html', context)

"""
Purpose: Used in dashboard.js asynchronous AJAX call to retrieve direct children location (either Region/Cluster)
of the location chosen in dashboardForm (Dashboard/forms.py) choicefield. The database accessed is the Location Table

Request Parameters: parent location id
Returns: JSON object -> list of children's location IDs

Use: dashboard.js -> function observe()
"""
def ajaxLocation(request):
    locations_to_render = []
    location_id = request.GET.get('location_id')
    # location_type = request.GET.get('location_type')
    query_locations = Location.objects.filter(parentLocID = location_id)
    for loc in query_locations:
        locations_to_render.append(str(loc.locationID))
    return JsonResponse({'locations': locations_to_render})

"""
Purpose: Used in dashboard.js to retrieve complete & incomplete patient numbers used in chart.js 
based on the location specified in the Choicefield. The database accessed is the 
PatientAssessment table, HouseHold Table and Location Table (linked together through foreign keys)

Request Parameters: countryID, regionID, clusterID
Returns: JSON object -> a list of 2 elements: the first element is the number of COMPLETE assessments, 
the second element is a the number of INCOMPLETE assessments. 

Use: dashboard.js -> function get_data(countryID, regionID, clusterID)
"""
def ajaxData(request):
    countryID = request.GET.get('countryID')
    regionID = request.GET.get('regionID')
    clusterID = request.GET.get('clusterID')
    if clusterID != '0':
        incomplete = PatientAssessment.objects.filter(
            questionnaireStatus = "INCOMPLETE", 
            assess_patientID__householdID__parentLocID = int(clusterID)).count()
        complete = PatientAssessment.objects.filter(
            questionnaireStatus = "COMPLETE",
            assess_patientID__householdID__parentLocID = int(clusterID)).count()
    elif regionID != '0':
        incomplete = PatientAssessment.objects.filter(
            questionnaireStatus = "INCOMPLETE",
            assess_patientID__householdID__parentLocID__parentLocID = int(regionID)).count()
        complete = PatientAssessment.objects.filter(
            questionnaireStatus = "COMPLETE",
            assess_patientID__householdID__parentLocID__parentLocID = int(regionID)).count()       
    elif countryID != '0':
        incomplete = PatientAssessment.objects.filter(
            questionnaireStatus = "INCOMPLETE",
            assess_patientID__householdID__parentLocID__parentLocID__parentLocID = int(countryID)).count()
        complete = PatientAssessment.objects.filter(
            questionnaireStatus = "COMPLETE",
            assess_patientID__householdID__parentLocID__parentLocID__parentLocID = int(countryID)).count()
    elif countryID == '0':
        incomplete = PatientAssessment.objects.filter(questionnaireStatus = "INCOMPLETE").count()
        complete = PatientAssessment.objects.filter(questionnaireStatus = "COMPLETE").count() 
    return JsonResponse({'data': [complete, incomplete]})


"""
Purpose: Used in dashboard.js to retrieve incomplete patient data for the Incomplete Patient table. The database 
accessed is PatientAssesment Table, Questionnaire Table, Patient Table (linked through Foreign Keys)

Request Parameters: countryID, regionID, clusterID
Returns: JSON object -> a list of dicts that hold patient id, patient assessment start date, 
questionnaire name and questionnaire id of a single patient entity whose assessment status is "INCOMPLETE" and 
belongs to the specified location

JSON OBJECT RETURNED: {"data":[{},{},{}]}

Use: dashboard.js -> function get_patient_data(countryID, regionID, clusterID)
"""
def ajaxIncompletePatients(request):
    countryID = request.GET.get('countryID')
    regionID = request.GET.get('regionID')
    clusterID = request.GET.get('clusterID')
    if clusterID != '0':
        incomplete_patients = PatientAssessment.objects.filter(
            questionnaireStatus = "INCOMPLETE", 
            assess_patientID__householdID__parentLocID = int(clusterID)).select_related()
    elif regionID != '0':
        incomplete_patients = PatientAssessment.objects.filter(
            questionnaireStatus = "INCOMPLETE",
            assess_patientID__householdID__parentLocID__parentLocID = int(regionID)).select_related()
    elif countryID != '0':
        incomplete_patients = PatientAssessment.objects.filter(
                    questionnaireStatus = "INCOMPLETE",
                    assess_patientID__householdID__parentLocID__parentLocID__parentLocID = int(countryID)).select_related()
    elif countryID == '0':
        incomplete_patients = PatientAssessment.objects.filter(questionnaireStatus = "INCOMPLETE").select_related()
    data = []
    for patient in incomplete_patients:
        data.append({
            'patient_id' : patient.assess_patientID.patientID,
            'questionnaire_id': patient.assess_questionnaireID.questionnaireID,
            'questionnaire_name': patient.assess_questionnaireID.questionnaireName,
            'start': patient.start
        })
    return JsonResponse({'data':data})

templates/ans_qnn.html
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">  
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <title>Add Answers</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        <h1>Add Answers to Question</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-8">
                    {{form.customAnswer|as_crispy_field}}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Add Answer</button>
            <a href="/questionnaires/create/question/{{questionnaire_id}}" class="btn btn-success">Done</a>
        </form>

        <div>
            <table>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Answers</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for answer in answers%}
                     <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ answer.answerID.answerString }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </table>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% include "footer.html" %}
</body>

</html>

templates/enumerator_table.html
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <title>Enumerator</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <h2 class="title">Enumerator Registration</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
            
            <form method="post" action='#'>
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm">
                        {{form.prefix | as_crispy_field }}
                    </div>
                    <div class="col-sm">
                        {{form.suffix | as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{form.firstName | as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{form.lastName | as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm">
                        {{form.organization | as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{form.date_of_birth | as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{form.active_flag | as_crispy_field }}
                    </div>
                    {{form.errors}}
                </div>             
                <input type="submit" value="Add" name="Next" class="btn btn-success"/>
            </form>
            
            </div>
        </div>

    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% include "footer.html" %}
</body>

</html>

templates/enumerator_token.html
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <title>Document</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <h2 class="title">Add Enumerator</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <form method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success" >Next</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h3 style="margin-top: 100;">Registered Enumerators</h3>
                <table class="table table-responsive table-hover">
                    <thead>
                        <tr>
                            <th>
                                Username
                            </th>
                            <th>
                                Organization
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for enum in enumerators%}
                        <tr style="width:100%;">
                            <td>{{enum.username}}</td>
                            <td>{{enum.organization}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% include "footer.html" %}
</body>

</html>

templates/footer.html
<div id=footer style="height:6rem; width:auto; background-color:white; margin-top: 100px; margin-bottom: 0;">
</div>

templates/logic.html
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/questionnaires.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">  

    <title>Add Questions</title>
</head>
<body>
  {% include "navbar.html" %}
    <div class="container">
        <div class="col-sm">
        <h1 class="title">Add Logic</h1>
        <p id="questionnaire_id" hidden> {{ questionnaire_id }}</p>
        <form method="POST">
            {% csrf_token %}
            {{ logicForm | crispy }}
            <div  id='QA'>
                {{ formset.management_form }}
                {% for form in formset %}   
                    <div class='table qrelForm'>
                        {{ form | crispy }}
                    </div>
                    {% endfor %}
                    <input type="button" value="Add More" id="add_more" class="btn btn-primary">
            </div>
            <br>
                <button type="submit" class="btn btn-primary" id="done_add">Done and Add More</button>
                <a href="/questionnaires" class="btn btn-success">Finished</a>
            </form>        
            </div>
            <div class="col-sm">
              <br>
                <table class="table">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Current Question</th>
                      <th scope="col">Next Question</th>
                      <th scope="col">Relationship</th>
                    </tr>
                  </thead>
                  <tbody id="table_body">
                    {% for entry in logic %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{ entry.logic_questionID.questionString }}</td>
                      <td>{{ entry.next_qID.questionString }}</td>
                      <td>{{ entry.rel_type }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>       
            </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/logic.js' %}"></script>  
    {% include "footer.html" %}
  </body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href= "{% url 'home' %}" >Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Builder:questionnaires' %}">Questionnaires</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Reports:report_location'%}">Reports</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Dashboard:dashboard'%}">Dashboard</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Enumerator:getToken'%}">Registration</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Locations:createLocation'%}">Location</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout'%}"><strong>Logout</strong></a>
          </li>
      </ul>
    </div>
  </nav>

templates/questionnaires.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/questionnaires.css' %}" />
    <title>Questionnaires</title>
</head>
{% include "navbar.html" %}
<body>
  
  <div class="container">
    <h2 class="title">Questionnaires</h2>
    
    <a class="btn btn-primary button-margin" href={% url 'Builder:newQuestionnaire' %}>New Questionnaire</a>
    <a class="btn btn-warning button-margin" href={% url 'Builder:setActiveQnn' %}>Set Active Questionnaires</a>

    <h3>List of Questionnaires and Questions</h3>
    {% for data in data %}

    <div class="accordion" id="accordionExample">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h2 class="mb-0">

            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#target{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseOne">
              {{data.questionnaireName}}
            </button>
            <a href="https://system-engineering.herokuapp.com/questionnaires/create/question/{{data.questionnaireID}}" class="small-font">Edit</a>
            {% if data.active_flag == 1 %}
            <p class="active">Active</p>
            {% endif %}

          </h2>
        </div>
        <div id="target{{ forloop.counter }}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
            <ol>
              {% for stuff in data.question%}
              <li>{{ stuff.1.1}}</li>
              {% endfor %}
            </ol>
            <p></p>
            
          </div>
        </div>
      </div>
      </div>
      {% endfor %}
  </div>
  
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% include "footer.html" %}
</body>
</html>